export const imageGridCards = [
  {
    id: "2568339",
    name: "Biryani",
    image: "PC_Mweb/Biryani.png",
    link: "https://www.swiggy.com/collections/83639",
  },
  {
    id: "2568312",
    name: "Cakes",
    image: "PC_Mweb/Cake.png",
    link: "https://www.swiggy.com/collections/83655",
  },
  {
    id: "2568016",
    name: "Pizzas",
    image: "PC_Mweb/Pizza.png",
    link: "https://www.swiggy.com/collections/83631",
  },
  {
    id: "2568574",
    name: "Burgers",
    image: "PC_Mweb/Burger.png",
    link: "https://www.swiggy.com/collections/83637",
  },
  {
    id: "2568346",
    name: "Noodles",
    image: "PC_Mweb/Noodles.png",
    link: "https://www.swiggy.com/collections/80463",
  },
  {
    id: "2568142",
    name: "Dosa",
    image: "PC_Mweb/Dosa.png",
    link: "https://www.swiggy.com/collections/80424",
  },
  {
    id: "2568034",
    name: "Rolls",
    image: "PC_Mweb/Rolls.png",
    link: "https://www.swiggy.com/collections/83669",
  },
  {
    id: "2568341",
    name: "Pastry",
    image: "PC_Mweb/Pastry.png",
    link: "https://www.swiggy.com/collections/80355",
  },
  {
    id: "2568353",
    name: "Momos",
    image: "PC_Mweb/Momo.png",
    link: "https://www.swiggy.com/collections/80461",
  },
  {
    id: "2568041",
    name: "Pasta",
    image: "PC_Mweb/Pasta.png",
    link: "https://www.swiggy.com/collections/80479",
  },
  {
    id: "2568015",
    name: "Chole Bhature",
    image: "PC_Mweb/Chole Bhature.png",
    link: "https://www.swiggy.com/collections/80382",
  },
  {
    id: "2568359",
    name: "Paratha",
    image: "PC_Mweb/Paratha.png",
    link: "https://www.swiggy.com/collections/80475",
  },
  {
    id: "2568330",
    name: "Shawarma",
    image: "PC_Mweb/Shawarma.png",
    link: "https://www.swiggy.com/collections/80402",
  },
  {
    id: "2568324",
    name: "Khichdi",
    image: "PC_Mweb/Khichdi.png",
    link: "https://www.swiggy.com/collections/80455",
  },
  {
    id: "2568326",
    name: "Ice Cream",
    image: "PC_Mweb/Ice Cream.png",
    link: "https://www.swiggy.com/collections/83640",
  },
  {
    id: "2568332",
    name: "Coffee",
    image: "PC_Mweb/Coffee.png",
    link: "https://www.swiggy.com/collections/83659",
  },
  {
    id: "2568337",
    name: "Pav Bhaji",
    image: "PC_Mweb/Pav Bhaji.png",
    link: "https://www.swiggy.com/collections/80362",
  },
  {
    id: "2568314",
    name: "Idli",
    image: "PC_Mweb/Idli.png",
    link: "https://www.swiggy.com/collections/80440",
  },
  {
    id: "2568033",
    name: "Kebabs",
    image: "PC_Mweb/Kebab.png",
    link: "https://www.swiggy.com/collections/80451",
  },
  {
    id: "2568573",
    name: "Gulab Jamun",
    image: "PC_Mweb/Gulab Jamun.png",
    link: "https://www.swiggy.com/collections/80430",
  },
];
